pipeline {
    agent {
        docker{
            image 'ruby'
        }
    }

    stages {
        stage('prep'){
            steps {
                sh '  cd api && bundle install'
            }
        }
        stage('testing') {
            steps {
                sh 'cd api '
                sh 'rspec'
            }
        }
    }
}
