pipeline {
    agent {
        docker{
            image 'ruby'
            args '--network rocklov-network'

        }
    }

    stages {
        stage('prep'){
            steps {
                sh '  cd api && bundle install'
            }
        }
        stage('testing') {
            steps {
                sh 'cd api && rspec'
            }
            
        }

      
     
    post{
        always {
              junit 'api/relatorio/report.xml'

        }
    }
}
