pipeline {
    agent {
        docker{
            image 'ruby'
            args '--network rocklov-network'

        }
    }

    stages {
        stage('prep'){
            steps {
                sh '  cd api && bundle install'
            }
        }
        stage('testing') {
            steps {
                sh 'cd api && rspec'
            }
            
        }

        stage('UAT')
        steps {
            echo "aguardando teste de aceitação"
            echo "podemos ir para produção"
           
        }

    }


       stage('Prod')
        steps {
            echo "api pronta para produção"
            
        }

    }
     
    post{
        always {
              junit 'api/relatorio/report.xml'

        }
    }
}
